### ISSUE TITLE
#r doesn't work as expected with local libraries

### ISSUE THREAD

**Issue by mehmetakbulut** [dotnet/try#609]
#### Describe the bug
This issue has two parts, not sure if they are related:
1) Attempting to load a locally available library using #r with an absolute path fails partially. An error will be printed as if the #r command failed but namespace is available and types are usable if included with a `using` statement. Regardless, autocompletion of anything involving this local library doesn't work except when writing the `using` statement.
2) Attempting to load a locally available library using #r with a relative path fails completely. It will print out the standard file not found error. I'm not certain if this is intended to work so a clarification would be great. Without using an absolute path, certain (all?) system packaged libraries seem to be loadable just fine which makes me think there is some special handling concerning those.

Both issues are present in Jupyter Notebook, Lab and Console. Tried with various dlls that were either originally downloaded with nuget or built locally.

#### Did this error occur while using `dotnet try` or online?
- [X] `dotnet-try` (jupyter)
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other: Potential issue with .NET C# Kernel for Jupyter

#### Screenshots
No screenshots but:

Windows
```
#r "C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll"

Invalid: Command: #r C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll
```

Linux
```
#r "/home/mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll"

Invalid: Command: #r /home/mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll
```

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [X] Linux (Ubuntu 18.04)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
This should be fixed by #600.

**Comment by mehmetakbulut** [comment]
Thank you @jonsequitur. Do you have any clue which release / when the contents of that PR will be available on a feed?

**Comment by jonsequitur** [comment]
Every PR that merges produces a new package in this feed: https://dotnet.myget.org/F/dotnet-try/api/v3/index.json. You can grab the latest by running this in your console:

```console
> dotnet tool update -g dotnet-try --add-source https://dotnet.myget.org/F/dotnet-try/api/v3/index.json
```

**Comment by jonsequitur** [comment]
The fix for this is now available in MyGet feed. Please give it a try and let us know if you see any issues.

**Comment by mehmetakbulut** [comment]
It looks like the error is no longer displayed with absolute paths but behavior is same as before (i.e. autocompletion doesn't work for types from the imported library)

Relative paths still don't seem to be working. (tried referencing from both jupyter's workspace root and kernel's working directory)

**Comment by jonsequitur** [comment]
Autocomplete support is not complete so this isn't indicative of a loading failure. Does code compile successfully against the imported library?

**Comment by mehmetakbulut** [comment]
Gotcha. Yes, code compiles great when importing libraries with absolute paths.

How about relative paths? I see them working fine in csi but with .NET Kernel and Jupyter, it complains that the path is wrong. (same on both Win10 and Ubuntu 18.04)

**Comment by jonsequitur** [comment]
I don't see why a relative path shouldn't work but maybe the working directory is wrong or unclear. I'll give it a look.

**Comment by bryanrcarlson** [comment]
I'm seeing this error in version 1.0.19553.4:

```
#r "C:\Dev\Projects\CafModelingRegionalSoilConditioningIndex\Csip\src\dotnet\Csip.Common\bin\Debug\netstandard2.1\Csip.Common.dll"
Invalid: Command: #r C:\Dev\Projects\CafModelingRegionalSoilConditioningIndex\Csip\src\dotnet\Csip.Common\bin\Debug\netstandard2.1\Csip.Common.dll
```

When I update to 1.0.19620.2 via:

```
> dotnet tool update -g dotnet-try --add-source https://dotnet.myget.org/F/dotnet-try/api/v3/index.json

Tool 'dotnet-try' was successfully updated from version '1.0.19553.4' to version '1.0.19620.2'.
```

The error goes away, but only because the kernel crashes.

```
[W 09:22:55.774 LabApp] KernelRestarter: restart failed
[W 09:22:55.774 LabApp] Kernel bb768025-c107-4a3e-b5fa-84856efe62da died, removing from map.
[W 09:23:40.784 LabApp] Timeout waiting for kernel_info reply from bb768025-c107-4a3e-b5fa-84856efe62da
[E 09:23:40.784 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: bb768025-c107-4a3e-b5fa-84856efe62da)
[E 09:23:40.785 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: bb768025-c107-4a3e-b5fa-84856efe62da)
```

**Comment by jonsequitur** [comment]
@bryanrcarlson This bug was fixed in #609 but the fix is only available in the new `dotnet-interactive`, which is in the same MyGet feed as the `dotnet-try`. I've updated the install instructions here: https://github.com/dotnet/try/blob/master/NotebooksLocalExperience.md.

Give that a try.

**Comment by bryanrcarlson** [comment]
@jonsequitur That seemed to have fixed it! Thanks!
