### ISSUE TITLE
Output not visible

### ISSUE THREAD

**Issue by Rajat90** [dotnet/try#833]
Hello,

I tried running my first sample code and I was not able to see the output.
It shows red line at the output pane only and nothing is written in that.

Did this error occur while using `dotnet try` or online?
`dotnet-try`

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 

![image](https://user-images.githubusercontent.com/39190864/80863091-0ec65880-8c7a-11ea-98f8-95abcdb6bfd1.png)

  
Chrome

**Comment by colombod** [comment]
Can you share your repro?

**Comment by jonsequitur** [comment]
@Rajat90 Which version of `dotnet-try` are you using and can you include the output you get from running `dotnet --info` on the command line?

Thanks.

**Comment by surfsky** [comment]
I meet the same error:

<img width="1036" alt="internal-server-error" src="https://user-images.githubusercontent.com/3415764/83248624-ef1e4380-a1d7-11ea-8d02-6fbcb941574c.png">

in mac safari and chrome

<img width="634" alt="dotnet" src="https://user-images.githubusercontent.com/3415764/83248771-2987e080-a1d8-11ea-86ea-6be81199f20a.png">

**Comment by colombod** [comment]
We are addressing a bug that arise when using dotnet sdk 3.1.300, this issue might be related to #842 .

**Comment by colombod** [comment]
We released a new tool on the myget feed, could you see if following instructions to [install latest master](https://github.com/dotnet/try/blob/master/DotNetTryLocal.md#installing-preview-builds-from-master) addresses your issue?

**Comment by dagilleland** [comment]
@colombod - I was getting the same issue with it being blocked out with red, and installing the latest master did address the issue for me. Thanks!

**Comment by colombod** [comment]
> @colombod - I was getting the same issue with it being blocked out with red, and installing the latest master did address the issue for me. Thanks! 

Thank you for letting me know!

**Comment by colombod** [comment]
> Hello,
> 
> 
> 
> I tried running my first sample code and I was not able to see the output.
> 
> It shows red line at the output pane only and nothing is written in that.
> 
> 
> 
> Did this error occur while using `dotnet try` or online?
> 
> `dotnet-try`
> 
> 
> 
> 
> 
> #### What kind of error was it?
> 
> - [ ] User Interface (UI):  For example the output never displayed 
> 
> 
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/39190864/80863091-0ec65880-8c7a-11ea-98f8-95abcdb6bfd1.png)
> 
> 
> 
>   
> 
> Chrome
> 
> 

Are you still experiencing the issue? Don’t know if I checked already but make sure the tool installed is the Microsoft.dotnet-interactive

**Comment by PatrickMcvay** [comment]
I am still experiencing the issue. I have tried uninstalling and re-installing. 

![image](https://user-images.githubusercontent.com/19638117/87450728-80991780-c5c4-11ea-8a4e-46c57648cf61.png)


dotnet --info results:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015178
 Commit:    60cb58d3b1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015178\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  1.1.13 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.515 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


dotnet-try --version results:

1.0.20363.2+29fa4e6dab6c6a3e655b3ba11050e88c44ca1f14

**Comment by PatrickMcvay** [comment]
I also tried updating .netcore version to:
  Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

Still have the same issue though

**Comment by colombod** [comment]
Is it happening only on first run or is this blocking any run at all?

**Comment by jagrut-patel** [comment]
I am facing same issue.

1. Cloned **https://github.com/dotnet/try-samples** 
2. Installed **dotnet try**
    `dotnet tool uninstall -g Microsoft.dotnet-try`
    Tool 'microsoft.dotnet-try' (version '1.0.20370.1') was successfully uninstalled.
3. dotnet try version shows
    1.0.20380.1+6cab840964e654973143de0f0a0ea87dafd0404f
4. dotnet info

   .NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by EddyAlleman** [comment]
Hi colombod,
Your suggestion 
"We released a new tool on the myget feed, could you see if following instructions to install latest master addresses your issue?"
worked for me. Thanks a lot!

here are my installation details:
dotnet tool install -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-try
		Tool 'microsoft.dotnet-try' (version '1.0.20419.2') was successfully installed.
		
		dotnet --info
		.NET Core SDK (reflecting any global.json):
		 Version:   3.1.401
		 Commit:    5b6f5e5005
		
		Runtime Environment:
		 OS Name:     Windows
		 OS Version:  10.0.18363
		 OS Platform: Windows
		 RID:         win10-x64
		 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\
		
		Host (useful for support):
		  Version: 3.1.7
		  Commit:  fcfdef8d6b
		
		.NET Core SDKs installed:
		  2.1.402 [C:\Program Files\dotnet\sdk]
		  3.1.400 [C:\Program Files\dotnet\sdk]
		  3.1.401 [C:\Program Files\dotnet\sdk]
		
		.NET Core runtimes installed:
		  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
		  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
		  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
		  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
		  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
		  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
		  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
		  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
		  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
		
		To install additional .NET Core runtimes or SDKs:
		  https://aka.ms/dotnet-download

I hope this can help pinpointing the problem Patrick too.

cheers 
Eddy

**Comment by TomaszKot11** [comment]
For me, it stopped working...

**Comment by abdou31** [comment]
This command fix the problem for me :
> dotnet tool install -g Microsoft.dotnet-try --version=1.0.20419.2

**Comment by pachecogon** [comment]
> This command fix the problem for me :
> 
> > dotnet tool install -g Microsoft.dotnet-try --version=1.0.20419.2

For me, both versions give me the same error. 

-version '1.0.21110.1'
-version '1.0.20474.1'

If I run this:
 >dotnet tool install -g Microsoft.dotnet-try --version=1.0.20419.2
 I get the following warning: 
>warning NU1603: restore depends on Microsoft.dotnet-try (>= 1.0.20419.2) but Microsoft.dotnet-try 1.0.20419.2 was not found. An approximate best match of Microsoft.dotnet-try 1.0.20474.1 was resolved.
You can invoke the tool using the following command: dotnet-try

**Comment by Benarrow** [comment]
> > This command fix the problem for me :
> > > dotnet tool install -g Microsoft.dotnet-try --version=1.0.20419.2
> 
> For me, both versions give me the same error.
> 
> -version '1.0.21110.1'
> -version '1.0.20474.1'
> 
> If I run this:
> 
> > dotnet tool install -g Microsoft.dotnet-try --version=1.0.20419.2
> 
> I get the following warning:
> 
> > warning NU1603: restore depends on Microsoft.dotnet-try (>= 1.0.20419.2) but Microsoft.dotnet-try 1.0.20419.2 was not found. An approximate best match of Microsoft.dotnet-try 1.0.20474.1 was resolved.
> > You can invoke the tool using the following command: dotnet-try

Hello, 
I have met the same problem, but it seems that when you uninstalled all the .NET 5.0+ on your computer, and run `dotnet try verify` before you start `dotnet try`, the red area would disappear.

**Comment by mkuehn10** [comment]
I tried all the solutions in this thread and it still occurs.

`PS C:\users\michael.kuehn\source\repos\try-demo> dotnet try verify
Verifying...

C:\users\michael.kuehn\source\repos\try-demo\NewProject.md
----------------------------------------------------------

C:\users\michael.kuehn\source\repos\try-demo\PassingArgs.md
-----------------------------------------------------------
  Checking Markdown...
    ✓  Line 16: C:\users\michael.kuehn\source\repos\try-demo\Snippets\Program.cs (in project C:\users\michael.kuehn\source\repos\try-demo\Snippets\Snippets.csproj)

  Compiling samples for region "Main"

Unhandled exception: System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 9, the log file has version 13.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 9, the log file has version 13.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 138
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog() in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 127
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 112
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\RebuildablePackage.cs:line 22
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\PackageBuilder.cs:line 163
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext() in D:\workspace\_work\1\s\WorkspaceServer\PackageRegistry.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\PackageRegistry.cs:line 92
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.CompileWorker(Workspace workspace, BufferId activeBufferId, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 412
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.Compile(WorkspaceRequest request, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 193
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.Compile(WorkspaceRequest request, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\WorkspaceServerMultiplexer.cs:line 26
   at MLS.Agent.CommandLine.VerifyCommand.Compile(Session session, MarkdownProcessingContext context) in D:\workspace\_work\1\s\MLS.Agent\CommandLine\VerifyCommand.cs:line 193
   at MLS.Agent.CommandLine.VerifyCommand.Do(VerifyOptions verifyOptions, IConsole console, StartupOptions startupOptions, MarkdownProcessingContext context) in D:\workspace\_work\1\s\MLS.Agent\CommandLine\VerifyCommand.cs:line 84
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MLS.Agent.CommandLine.CommandLineParser.<>c__DisplayClass7_0.<<Create>b__2>d.MoveNext() in D:\workspace\_work\1\s\MLS.Agent\CommandLine\CommandLineParser.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()`

`PS C:\users\michael.kuehn\source\repos\try-demo> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.406
 Commit:    3a48fd6fe5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.406\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download`

**Comment by girodg** [comment]
> rst run or is this blocking any run at all?

any luck resolving this?

**Comment by FChaillot** [comment]
Same problem. Is the project dead ?

 System.NotSupportedException: Unsupported log file format. Latest supported version is 9, the log file has version 14.

**Comment by colombod** [comment]
Hi, the project is not dead but is going under a big transformation.

**Comment by melodyjay** [comment]
Can you give me a job

**Comment by YoussefMorad1** [comment]
No solution for this so far?

**Comment by chiragthakuri** [comment]
got the same issue

![image](https://github.com/user-attachments/assets/e162e0d3-64a3-4eaf-a0e4-5d3147ad4e7c)
